version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: ms-consolidacao-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartola
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  app:
    image: fredsonchaves07/ms-consolidacao
    container_name: ms-consolidacao-app
    restart: always
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"